import numpy
from numba import njit
from .utils import (
    indc_int_type, cplx_type, indc_mod,
    acq_mat, ps0, z2inv, pauli_combine, pauli_transform, binary_repr,
    random_pauli, random_clifford, map_to_state, state_to_map, clifford_rotate,
    stabilizer_measure, stabilizer_postselect, stabilizer_project, stabilizer_expect, 
    stabilizer_entropy, mask_qubits, merge_qubits, as_qubits)
from .paulialg import (Pauli, PauliList, PauliPolynomial, pauli, paulis)

class CliffordMap(PauliList):
    '''Represents a Clifford map. This is a subclass of PauliList.
    
    Idea: a most general Clifford transformation is specified by the operator
    mapping (how each single Pauli maps to under the trnasformation):
    X0 -> U X0 U^dagger = Pauli[g0,p0]
    Z0 -> U Z0 U^dagger = Pauli[g1,p1]
    X1 -> U X1 U^dagger = Pauli[g2,p2]
    Z1 -> U Z1 U^dagger = Pauli[g3,p3]
    ....
    The operators [g0,g1,g2,g3,...] forms a PauliList.

    Parameters:
    gs: int (2*N, 2*N) - strings of Pauli operators to be mapped to.
    ps: int (2*N) - phase indicators of Pauli operators to be mapped to.'''
    def __init__(self, *args, **kwargs):
        # call superclass PauliList to handle arguments
        super(CliffordMap, self).__init__(*args, **kwargs)

    def embed_qubits(self, qubits, inds = None):
        '''Embed a Clifford map into a larger set of qubits.
        
        Parameters:
        qubits: int (N) - larger target set of qubits.
            (User must ensure that qubits is sorted and self.qubits is its subset.)
        inds: int (N) - (optional) index of current qubits in target qubits set.

        Returns:
        Clifford map with embedded qubits.'''
        qubits = as_qubits(qubits)
        if numpy.array_equal(qubits, self.qubits):
            return self
        if inds is None:
            inds = numpy.searchsorted(qubits, self.qubits)
        gs = numpy.eye(2*len(qubits), dtype=indc_int_type)
        inds2 = numpy.column_stack([2*inds, 2*inds+1]).flatten()
        gs[numpy.ix_(inds2, inds2)] = self.gs
        ps = numpy.zeros(2*len(qubits), dtype=indc_int_type)
        ps[inds2] = self.ps
        self.gs = gs
        self.ps = ps
        self.qubits = qubits
        return self
    
    def prune_qubits(self):
        '''Prune the qubits of a Clifford map.
        
        Returns:
        Clifford map with pruned qubits.'''
        gs_diff = self.gs - numpy.eye(2*self.N, dtype=indc_int_type)
        mask = ((gs_diff[0::2]!=0) | (gs_diff[1::2]!=0)).any(axis=1)
        mask2 = numpy.repeat(mask, 2)
        self.gs = self.gs[numpy.ix_(mask2, mask2)]
        self.ps = self.ps[mask2]
        self.qubits = self.qubits[mask]
        return self

    def __repr__(self):
        if self.N == 0:
            return 'CliffordMap()'
        xz = {0:'X',1:'Z'}
        q_str = [str(q) for q in self.qubits]
        q_len = str(max(len(q) for q in q_str))
        dis = '{}{:<'+q_len+'}-> {}'
        if self.N <= 10:
            lns = [dis.format(xz[i%2], q_str[i//2], pauli) for i, pauli in enumerate(self)]
            return 'CliffordMap(\n{})'.format('\n'.join(lns)).replace('\n','\n  ')
        else:
            lns1 = [dis.format(xz[i%2], q_str[i//2], pauli) for i, pauli in zip(range(10), self[:10])]
            lns2 = [dis.format(xz[i%2], q_str[i//2], pauli) for i, pauli in zip(range(self.L-10, self.L), self[-10:])]
            return 'CliffordMap(\n{}\n   ...\n{})'.format('\n'.join(lns1),'\n'.join(lns2)).replace('\n','\n  ')
    
    def copy(self):
        return CliffordMap(self.gs.copy(), self.ps.copy(), qubits=self.qubits.copy())

    def to_state(self, r=0):
        '''Interprete the Clifford map as a stabilizer state, such that the
            state is generated by the map from the zero state.'''
        gs, ps = map_to_state(self.gs, self.ps)
        return StabilizerState(gs, ps, r=r, qubits=self.qubits)

    def tensor_product(self, other):
        '''Tensor product two disjoint Clifford maps.
           (User must ensure that the two maps have disjoint qubit supports.)'''
        qubits, inds_me, inds_other = merge_qubits(self.qubits, other.qubits)
        N = len(qubits)
        gs = numpy.zeros((2*N, 2*N), dtype=indc_int_type)
        inds2_me = numpy.column_stack([2*inds_me, 2*inds_me+1]).flatten()
        inds2_other = numpy.column_stack([2*inds_other, 2*inds_other+1]).flatten()
        gs[numpy.ix_(inds2_me, inds2_me)] = self.gs
        gs[numpy.ix_(inds2_other, inds2_other)] = other.gs
        ps = numpy.zeros(2*N, dtype=indc_int_type)
        ps[inds2_me] = self.ps
        ps[inds2_other] = other.ps
        return CliffordMap(gs, ps, qubits=qubits)

    def compose(self, other):
        '''Returns the composition of this map with the other map. (in-place)
        Algorithm: tranforming the target Pauli operators in this map by the other map.
        
        Parameters:
        other: CliffordMap - other Clifford map to compose with.

        Returns:
        self: CliffordMap - the composition of this map with the other map.'''
        self.transform_by(other)
        return self

    def inverse(self):
        '''Returns the inverse of this Clifford map, (such that it composes with
        its inverse results in identity map).
        
        Returns:
        self: CliffordMap - the inverse of this Clifford map.'''
        gs_inv = z2inv(self.gs)
        _, ps_mis = pauli_combine(gs_inv, self.gs, self.ps)
        ps_inv = indc_mod(- ps_mis - ps0(gs_inv), 4)
        return CliffordMap(gs_inv, ps_inv, qubits=self.qubits)

class StabilizerState(PauliList):
    '''Represents a stabilizer state. This is a subclass of PauliList.
        rho = 1/2^r prod_{a=1}^{N-r} (1+ Pauli[g_a,p_a])/2

    The stabilizer state is specified by a stablizer tableau, as a binary matrix
    of the shape (2*N, 2*N).
        rows [0,r) - standby stabilizers
        rows [r,N) - active stabilizers (g_a)
        rows [N,N+r) - standby destabilizers
        rows [N+r,2*N) - active destabilizers
    The stabilizers and destablizers in the tableau forms a list of Pauli 
    operators, which can be represented as a subclass of PauliList.

    Parameters:
    gs: int (2*N, 2*N) - strings of Pauli operators in the stabilizer tableau.
    ps: int (2*N) - phase indicators (should only be 0 or 2).
    r:  int  - number of logical qubits (log2 rank of density matrix)
        (r can only be provided as a keyword argument)'''
    def __init__(self, *args, **kwargs):
        # extract r and remove it from kwargs, if present.
        # otherwise, set r = 0 as pure state by default.
        self.r = kwargs.pop('r', 0) 
        # call superclass PauliList to handle remaining arguments
        super(StabilizerState, self).__init__(*args, **kwargs)

    def embed_qubits(self, qubits, inds = None):
        '''Embed a stabilizer state into a larger set of qubits. (in-place)
        
        Parameters:
        qubits: int (N) - larger target set of qubits.
            (User must ensure that qubits is sorted and self.qubits is its subset.)
        inds: int (N) - (optional) index of current qubits in target qubits set.

        Returns:
        self: StabilizerState - the embedded stabilizer state.'''
        qubits = as_qubits(qubits)
        if numpy.array_equal(qubits, self.qubits):
            return self
        if inds is None:
            mask = mask_qubits(self.qubits, qubits)
        else:
            mask = numpy.zeros(len(qubits), dtype=numpy.bool_)
            mask[inds] = True
        maskx = ~mask
        mask0 = numpy.zeros(len(qubits), dtype=numpy.bool_)
        mask_stb = numpy.concatenate([mask, mask0])
        maskx_stb = numpy.concatenate([maskx, mask0])
        mask_dst = numpy.concatenate([mask0, mask])
        maskx_dst = numpy.concatenate([mask0, maskx])
        state = self.to_map().embed_qubits(qubits, inds).to_state()
        self.gs = numpy.concatenate([
            state.gs[maskx_stb], state.gs[mask_stb], 
            state.gs[maskx_dst], state.gs[mask_dst]])
        self.ps = numpy.concatenate([
            state.ps[maskx_stb], state.ps[mask_stb], 
            state.ps[maskx_dst], state.ps[mask_dst]])
        self.qubits = qubits
        self.r += maskx.sum()
        return self

    def prune_qubits(self):
        '''Prune the qubits of a stabilizer state. (in-place)
        
        Returns:
        self: StabilizerState - the pruned stabilizer state.'''
        return stabilizer_state(self.stabilizers.prune_qubits())

    def __repr__(self):
        ''' will only show active stabilizers, 
            to see the full stabilizer tableau, convert to PauliList by [:] '''
        subrepr = repr(self.stabilizers).strip('[]')
        if subrepr == '':
            return 'StabilizerState()'
        else:
            return 'StabilizerState(\n {})'.format(subrepr).replace('\n','\n ')

    @property
    def stabilizers(self):
        return self[self.r:self.N]
    
    def copy(self):
        return StabilizerState(self.gs.copy(), self.ps.copy(), r=self.r, qubits=self.qubits.copy())

    def to_map(self):
        '''Interprete the stabilizer state as its encoding Clifford map.'''
        gs, ps = state_to_map(self.gs, self.ps)
        return CliffordMap(gs, ps, qubits=self.qubits)

    def measure(self, obs):
        '''Perform Pauli observable measurement on the stabilizer state.
           - sample measurement outcomes from:
                p(out_k = 0|rho) = (1 + Tr(rho obs_k))/2
                p(out_k = 1|rho) = (1 - Tr(rho obs_k))/2
           - collapse the state to the posterior state conditioned on 
             the measurement outcomes. (in-place update)
        
        Parameters:
        obs: PauliList or StabilizerState (only active stabilizers measured)

        Returns:
        out: int (L) - array of measurement outcomes of corresponding observables.
        log2prob: real - log2 probability of sampling this set of outcomes.'''
        if isinstance(obs, StabilizerState):
            obs = obs.stabilizers
        if not numpy.array_equal(self.qubits, obs.qubits):
            # merge and embed qubit support
            qubits, inds1, inds2 = merge_qubits(self.qubits, obs.qubits)
            self.embed_qubits(qubits, inds1) # in-place modification
            obs.embed_qubits(qubits, inds2) # in-place modification
        self.gs, self.ps, self.r, out, log2prob = stabilizer_measure(
            self.gs, self.ps, obs.gs, obs.ps, self.r)
        return out, log2prob

    def postselect(self, obs, out=None):
        '''Postselect the stabilizer state on a set of Pauli observables, 
           such that on the postselected state:
           - default behavior:     <obs_k> = +1,
           - with target outcomes: <obs_k> = (-1)^{out_k},
           The postselected state is in-place updated.
        
        Parameters:
        obs: PauliList or StabilizerState (only active stabilizers postselected)
        out: int (L) - array of target measurement outcomes of corresponding observables.
             default is None, meaning <obs_k> = +1.

        Returns:
        log2prob: real - log2 probability for postselection to succeed.'''
        if isinstance(obs, StabilizerState):
            obs = obs.stabilizers
        if out is None:
            obs_ps = obs.ps
        else: # encode target outcomes to operator phases
            obs_ps = indc_mod(obs.ps + 2*out, 4) # modify operator phases
        if not numpy.array_equal(self.qubits, obs.qubits):
            # merge and embed qubit support
            qubits, inds1, inds2 = merge_qubits(self.qubits, obs.qubits)
            self.embed_qubits(qubits, inds1) # in-place modification
            obs.embed_qubits(qubits, inds2) # in-place modification
        self.gs, self.ps, self.r, log2prob = stabilizer_postselect(
            self.gs, self.ps, obs.gs, obs_ps, self.r)
        return log2prob

    def expect(self, obs, z=1.):
        '''Evaluate expectation values of observables on the statilizer state.
        
        Parameters:
        obs: observable, can be Pauli, PauliList, PauliPolynomial, StabilizerState
        z: fugacity of operator weight, it is not used when obs is StabilizerState
           default is 1. Setting z = 3 for Pauli shadow tomography directly.

        Returns:
        out: output (depending on the type of obs)
            * Pauli: promote to PauliPolynomial
            * PauliPolynomial O: Tr(rho O z^|O|)
            * StabilizerState sigma: Tr(rho sigma) = p(sigma|rho)
            * PauliList [O_i]: [Tr(rho O_i z^|O_i|)]
        '''
        if isinstance(obs, Pauli):
            return self.expect(obs.as_polynomial()) # cast Pauli to PauliPolynomial
        elif isinstance(obs, PauliPolynomial):
            # cast PauliPolynomial to PauliList for expectation value calculation
            xs = self.expect(obs.as_list())
            if z != 1.: # if fugacity not 1, multiply by fugacity to the power of operweight
                zs = z ** obs.weight()
                xs = xs * zs
            return numpy.sum(obs.cs * xs) # combine expectation values by coefficients
        elif isinstance(obs, StabilizerState):
            rho = self.copy() # make a copy to avoid in-place update in postselection
            log2prob = rho.postselect(obs) # use post-selection to calculate Tr(rho obs)
            return 2. ** log2prob # convert log2 probability to probability
        # WARNING: PauliList instance must be placed after StabilizerState instance
        #          otherwise StabilizerState will be shadowed by PauliList as subclass
        elif isinstance(obs, PauliList):
            if not numpy.array_equal(self.qubits, obs.qubits):
                # merge and embed qubit support
                qubits, inds1, inds2 = merge_qubits(self.qubits, obs.qubits)
                self.embed_qubits(qubits, inds1) # in-place modification
                obs.embed_qubits(qubits, inds2) # in-place modification
            xs = stabilizer_expect(self.gs, self.ps, obs.gs, obs.ps, self.r)
            if z != 1.: # if fugacity not 1, multiply by fugacity to the power of operator weight
                zs = z ** obs.weight()
                xs = xs * zs
            return xs
        else:
            raise ValueError("Unsupported observable type: {}".format(type(obs)))

    def to_numpy(self, qubits = None):
        """Convert stabilizer state to numpy density matrix representation.
        Returns a (2^N, 2^N) array representing rho = 1/2^r prod_{a=1}^{N-r} (1+ Pauli[g_a,p_a])/2
        """
        stb_mats = self.stabilizers.to_numpy(qubits)
        dim = stb_mats.shape[1]
        rho = numpy.eye(dim, dtype=cplx_type)
        for mat in stb_mats:
            rho = rho @ (numpy.eye(dim, dtype=cplx_type) + mat) / 2
        return rho / rho.trace()

    def entropy(self, subsys = None):
        '''Entanglement entropy of the stabilizer state in a given region.

        Parameters:
        subsys: int (N_sub) - array of qubit indices in subsystem
            default is None, meaning the entire system. '''
        subsys = as_qubits(subsys)
        if subsys is None:
            mask = numpy.ones(self.N, dtype=numpy.bool_)
        else:
            if len(subsys) == 0:
                return 0
            else:
                mask = mask_qubits(subsys, self.qubits)
        return stabilizer_entropy(self.stabilizers.gs, mask)
    
    def sample(self, L, seed = None):
        '''Sample stabilizers from the stabilizer group.'''
        if seed is not None:
            numpy.random.seed(seed)
        C = numpy.random.randint(2, size=(L,self.N-self.r))
        gs, ps = pauli_combine(C, self.gs[self.r:self.N], self.ps[self.r:self.N])
        return PauliList(gs, ps, qubits=self.qubits)


    def get_prob(self, out):
        '''Evaluate the probability of getting a bit string readout.
           Assume computational basis measurement.'''
        if self.N != out.shape[0]:
            raise ValueError("readout size {} is incompatible with system size {}!".format(out.shape[0], self.N))
        return self.expect(basis_state(out, qubits=self.qubits))

    # !!! this function has exponential complexity.
    def as_polynomial(self):
        '''Expand stabilizer state as density matrix in PauliPolynomial representation.'''
        C = binary_repr(numpy.arange(2**(self.N-self.r)))
        gs, ps = pauli_combine(C, self.gs[self.r:self.N], self.ps[self.r:self.N])
        return PauliPolynomial(gs, ps, qubits=self.qubits) / 2**self.N

# ---- map constructors ----
def identity_map(qubits = None):
    '''construct identity Clifford map over qubits.'''
    qubits = as_qubits(qubits)
    N = 0 if qubits is None else len(qubits)
    gs = numpy.eye(2*N, dtype=indc_int_type)
    return CliffordMap(gs, qubits=qubits)

def random_pauli_map(qubits = None, seed = None):
    '''construct random Pauli map over qubits.'''
    qubits = as_qubits(qubits)
    N = 0 if qubits is None else len(qubits)
    gs = random_pauli(N, seed=seed) # shape (2*N, 2*N), mapping matrix
    if seed is not None:
        numpy.random.seed(seed)
    ps = 2 * numpy.random.randint(0,2,2*N, dtype=indc_int_type) # shape (2*N), phase indicator
    return CliffordMap(gs, ps, qubits=qubits)

def random_clifford_map(qubits = None, seed = None):
    '''construct random Clifford map of N qubits.
        drawn from N-qubit Clifford group uniformly.'''
    qubits = as_qubits(qubits)
    N = 0 if qubits is None else len(qubits)
    gs = random_clifford(N, seed=seed) # shape (2*N, 2*N), mapping matrix
    if seed is not None:
        numpy.random.seed(seed)
    ps = 2 * numpy.random.randint(0,2,2*N, dtype=indc_int_type) # shape (2*N), phase indicator
    return CliffordMap(gs, ps, qubits=qubits)

def clifford_rotation_map(gen):
    '''construct Clifford map from generator.'''
    gen = pauli(gen)
    gs = numpy.eye(2*gen.N, dtype=indc_int_type) # initialize
    ps = numpy.zeros(2*gen.N, dtype=indc_int_type) # initialize
    gs, ps = clifford_rotate(gen.g, gen.p, gs, ps)
    return CliffordMap(gs, ps, qubits=gen.qubits)

# ---- state constructors ----
def stabilizer_state(*stabilizers):
    '''Construct a stabilizer state from a list of stabilizers

    Parameters:
    stabilizers: PauliList or descriptions of stabilizers.'''
    stabilizers = paulis(*stabilizers) # parsing input to PauliList
    if stabilizers:
        # validity check:
        if not (acq_mat(stabilizers.gs) == 0).all():
            raise ValueError('stabilizers must all commute with each other.')
        state = maximally_mixed_state(stabilizers.N)
        state.gs, state.r = stabilizer_project(state.gs, numpy.flipud(stabilizers.gs), state.r)
        state.ps[state.r:state.N] = stabilizers.ps
        state.qubits = stabilizers.qubits
        return state
    else:
        return zero_state()

def zero_state(qubits = None):
    return identity_map(qubits).to_state()

def one_state(qubits = None):
    state = zero_state(qubits)
    state.ps[:state.N] = 2 # set stabilizer sign to -1
    return state

def basis_state(out, qubits = None):
    # out should be a binary array matching qubits,
    qubits = as_qubits(qubits)
    N = None if qubits is None else len(qubits)
    if isinstance(out, (int, numpy.integer)):
        if N is not None and N > 64:
            raise ValueError(f"Integer representation of bitstring is not supported for N = {N} > 64, use string representation instead.")
        out = binary_repr(numpy.array([out], dtype=numpy.uint64), width=N)[0]
    elif isinstance(out, str):
        if N is not None and len(out) != N:
            raise ValueError(f"bitstring length {len(out)} is incompatible with qubit number {N}!")
        out = numpy.array(list(out)).astype(indc_int_type)
    if N is None:
        N = len(out)
        qubits = as_qubits(N)
    state = zero_state(qubits)
    state.ps[:N] = 2 * out # use phase indicator to encode bit = 0/1 -> Z = +1/-1.
    return state

def maximally_mixed_state(qubits = None):
    state = zero_state(qubits)
    state.r = state.N
    return state

def ghz_state(qubits = None):
    qubits = as_qubits(qubits)
    N = 0 if qubits is None else len(qubits)
    if N > 0:
        stbs = [{qubits[i]:'Z', qubits[i+1]:'Z'} for i in range(N-1)]
        stbs.append({q:'X' for q in qubits})
        return stabilizer_state(paulis(*stbs, qubits=qubits))
    else:
        return zero_state(qubits)

def random_pauli_state(r=0, qubits = None, seed = None):
    return random_pauli_map(qubits, seed).to_state(r)

def random_clifford_state(r=0, qubits = None, seed = None):
    return random_clifford_map(qubits, seed).to_state(r)

def random_basis_state(qubits = None, seed = None):
    qubits = as_qubits(qubits)
    N = 0 if qubits is None else len(qubits)
    out = numpy.random.randint(0,2,N, dtype=indc_int_type)
    return basis_state(out, qubits=qubits)